### ISSUE TITLE
Bug - Cambiar contraste letra item boton redondo

### ISSUE THREAD

**Issue by AlejandraNGomez12** [MISW-4203-2023/Vinilos#116]
# Comportamiento esperado
En todos los listados que lleven el compomente de letra redonda, debe tener el contraste adecuado.

# Comportamiento actual
En todos los listados que llevan el compomente de letra redonda, no tienen el contraste adecuado.

# Pasos para reproducir el defecto
1. Activar la navegación con talkback en el dispositivo movil.
2. Navegar en la aplicación hasta el listado de coleccionista o de artista o de albumes.

# Evidencias
Screenshot 1
![image](https://github.com/MISW-4203-2023/Vinilos/assets/123990169/c062b0c1-af69-433b-b06d-dfb0bbcc89c3)

**Comment by wcuadrosuniandes** [comment]
Se ajustó el contraste de los botones redondos, al ejecutar de nuevo la prueba de accesibilidad no arroja ninguna sugerencia
![image](https://github.com/MISW-4203-2023/Vinilos/assets/123990169/0dfc28f0-fe2a-4b4f-b4db-8ebfca6f5577)
