### ISSUE TITLE
Bug - Cambiar Descripción de los Botones de Album

### ISSUE THREAD

**Issue by AlejandraNGomez12** [MISW-4203-2023/Vinilos#117]
# Comportamiento esperado
El botón que lleva al detalle de album dentro del listado de coleccionistas debe tener una decripción que contenga el nombre del Album.

# Comportamiento actual
El botón que lleva al detalle álbum dentro del listado de álbumtiene una descripción generica 

# Pasos para reproducir el defecto
1. Activar la navegación con talkback en el dispositivo movil.
2. Navegar en la aplicación hasta el listado de álbumes.
3. Seleccionar un álbum.

# Evidencias
Screenshot 1
![image](https://github.com/MISW-4203-2023/Vinilos/assets/123990169/fe0849c1-7d7d-47c4-a0ab-8b5a580c12bd)

**Comment by wcuadrosuniandes** [comment]
Se ajustó el titulo para que sea lista álbumes, y el botón para ir a álbum se modificó la descripción para que se agregue el nombre del álbum "Ir a álbum ${collect.name}", de esta forma al ejecutar de nuevo la prueba de accesibilidad no arroja ninguna sugerencia.
![image](https://github.com/MISW-4203-2023/Vinilos/assets/123990169/722b2beb-ba77-4e16-aa96-72c0b65d17b2)
