### ISSUE TITLE
Bug - Cambiar Descripción del titulo de la pagina y el boton de "Coleccionista"

### ISSUE THREAD

**Issue by AlejandraNGomez12** [MISW-4203-2023/Vinilos#121]
# Comportamiento esperado
El botón para volver al listado de coleccionistas debe tener una descripción unica, y el botón para el ir al detalle de cada coleccionista debe tener una descripción única.

# Comportamiento actual
El botón para volver al listado de coleccionistas no tiene una descripción unica, y el botón para el ir al detalle de cada coleccionista no tiene una descripción única.

# Pasos para reproducir el defecto
1. Activar el test Accesibilidad
2. Navegar en la aplicación hasta el listado de coleccionistas

# Evidencias
Screenshot 1
![image](https://github.com/MISW-4203-2023/Vinilos/assets/123990169/e60e757a-4cfb-4141-8bb4-935c038cae16)

**Comment by wcuadrosuniandes** [comment]
Se modificó el titulo y la descripción para que sea Listado coleccionistas, de esta forma al ejecutar de nuevo la prueba de accesibilidad no muestra sugerencias.
![image](https://github.com/MISW-4203-2023/Vinilos/assets/123990169/34d679fa-6924-48e6-b71a-00b77b75066b)
