### ISSUE TITLE
Bug - (TalkBack) Cambiar Descripción de las estrellas

### ISSUE THREAD

**Issue by AlejandraNGomez12** [MISW-4203-2023/Vinilos#124]
# Comportamiento esperado
El botón que lleva al detalle de artista dentro del listado de artista debe tener una decripción que contenga el nombre del artista.

# Comportamiento actual
Las estrellas que corresponden a la calificación del álbum en los comentarios, comparten la misma descripción

# Pasos para reproducir el defecto
1. Activar la navegación con talkback en el dispositivo movil.
2. Navegar en la aplicación hasta el listado de coleccionistas.
3. Seleccionar un coleccionista.
4. Ir al tab de comentarios.
5.Navegar por las estrellas del comentario

# Evidencias
Screenshot 1
![image](https://github.com/MISW-4203-2023/Vinilos/assets/123990169/eaf687a7-26c8-4b61-9824-e5ca9e305c56)

**Comment by wcuadrosuniandes** [comment]
Se ajustó el contentDescription de las estrellas para que tome el index del repeat
![image](https://github.com/MISW-4203-2023/Vinilos/assets/123990169/1f3f84bc-9c26-4e76-85e9-09fdaace7d56)
